### PR TITLE
Fix most cclasp compiler warnings

### PR DESCRIPTION
**Pull request by kpoeck**
* Fix warnings generated from clasp-builder
* Fix warnings building cclasp both loading and compiling
* Fix typo in `src/lisp/kernel/lsp/describe.lisp` declaring the same variable twice special

### CODE REVIEW

**Comment by kpoeck** [comment]
reviewing the log from the github action jnust for cclasp:
* loading gives 7 style warnings
* compilation is without any warning
the style warnings are all about not known types, probably from `typep-expansion` from compiler macro for `typep`
```lisp
2022-06-12T15:42:04.7196370Z Loading/compiling source: /Users/runner/work/clasp/clasp/src/lisp/kernel/contrib/Concrete-Syntax-Tree/Lambda-list/grammar-symbols.lisp
2022-06-12T15:42:05.6149820Z ;;; Warning: Undefined type KEYWORD-ALLOW-OTHER-KEYS
2022-06-12T15:42:05.6170930Z ;;; Warning: Undefined type KEYWORD-ALLOW-OTHER-KEYS
2022-06-12T15:42:05.9721300Z ; caught STYLE-WARNING:
2022-06-12T15:42:05.9764690Z ;   Undefined type KEYWORD-ALLOW-OTHER-KEYS
2022-06-12T15:42:05.9767300Z ;     at unknown location
2022-06-12T15:42:05.9767570Z ; 
2022-06-12T15:42:05.9801990Z ; caught STYLE-WARNING:
2022-06-12T15:42:05.9807660Z ;   Undefined type KEYWORD-ALLOW-OTHER-KEYS
2022-06-12T15:42:05.9809870Z ;     at unknown location
2022-06-12T15:42:05.9810210Z ; 
2022-06-12T15:43:22.8394480Z Loading/compiling source: /Users/runner/work/clasp/clasp/src/lisp/kernel/contrib/Cleavir/BIR/structure.lisp
2022-06-12T15:43:22.8843060Z ; caught STYLE-WARNING:
2022-06-12T15:43:22.8851160Z ;   Undefined type FUNCTION
2022-06-12T15:43:22.8853040Z ;     at unknown location
2022-06-12T15:43:22.8853550Z ; 
2022-06-12T15:43:24.5865820Z ;;; Warning: Undefined type LETI
2022-06-12T15:43:24.6339260Z ; caught STYLE-WARNING:
2022-06-12T15:43:24.6342470Z ;   Undefined type LETI
2022-06-12T15:43:24.6344660Z ;     at unknown location
2022-06-12T15:43:24.6345320Z ; 
2022-06-12T15:43:24.7169060Z ;;; Warning: Undefined type COME-FROM
2022-06-12T15:43:24.8127300Z ; caught STYLE-WARNING:
2022-06-12T15:43:24.8131410Z ;   Undefined type COME-FROM
2022-06-12T15:43:24.8133670Z ;     at unknown location
2022-06-12T15:43:24.8134110Z ; 
2022-06-12T15:43:24.9112870Z ; caught STYLE-WARNING:
2022-06-12T15:43:24.9116790Z ;   Undefined type JUMP
2022-06-12T15:43:24.9118990Z ;     at unknown location
2022-06-12T15:43:24.9119330Z ; 
2022-06-12T15:43:24.9915940Z ; caught STYLE-WARNING:
2022-06-12T15:43:25.0328500Z ;   Undefined type COME-FROM
2022-06-12T15:43:25.0330700Z ;     at unknown location
2022-06-12T15:43:25.0331110Z ; 

not sure what to do here, the style warning seem justified, but does that warrant reordering the code?

**Comment by kpoeck** [comment]
@Bike what is your opinion?

**Comment by Bike** [comment]
I have been unsure about that style warning for a while... I think it generally makes sense, but sometimes it's a bit much. We even warn in places SBCL doesn't, like for handler-bind with unknown types

**Comment by kpoeck** [comment]
I also thought about only warning if the type is not defined in the compilation-unit, but as you said, the typep won't be optimized. So currently I'd say a style warning is warranted

**Comment by kpoeck** [comment]
@Bike since we don't seem to be doing anything with the style warnings for unknown types, could you please check this pr as is? The Pr #1343 will have a conflict with this regarding clasp-builder.lisp, so i'd appreciate if it could be merged before (as long as the content is ok, obviously)

**Review by Bike — APPROVED** [review]
Few things. The "fixme" comment is unnecessary. I think it's fairly clear from context that it was meant to be `(not (or bclasp cclasp))`. You can test with that and if it works, just do that and don't leave the comment.
Similarly, the "assume system is meant" comment is better suited as a commit message. I don't think it really adds anything as a comment. And the change makes the all-modules comment nonsensical so that should be removed.
Finally, `defvar` is stylistically better than declaim special.
These are all minor things and I have fixed them on my end, so I will be merging.

**Comment by Bike** [comment]
Eck. Sorry, I merged this but then had to rebase so it's not marked as merged. See 0cadca00775d44d5a592901b049bbd49d0f8743c

**Pull request closed without merging**
