### PR TITLE
Implement char-downcase char-upcase correctly for unicode

### PR DESCRIPTION
**Pull request by kpoeck**
* implement proper char-downcase char-upcase for unicode
* regenerate…lower-case-p and upper-case-p from unicode data file
* tests

### CODE REVIEW

**Comment by kpoeck** [comment]
solves #1120

**Comment by Bike** [comment]
Does this construct a new locale object for each call? Does that use some kind of slow lookup?

**Comment by kpoeck** [comment]
Possibly constructs a new locale on every call. Will:
* define the locale as a constant
* compare runtimes

**Comment by kpoeck** [comment]
ok, now this is 1000 times quicker with the locale as a constant, @Bike please recheck

**Comment by Bike** [comment]
I wonder if we might want to be able to customize the locale. But I guess we can worry about that later. UTF-8 is pretty much definitely better than just ASCII. I'll merge this after pushing some changes I have.

**Pull request merged**
