### PR TITLE
define stat,fast (size,mtime.mode)

### PR DESCRIPTION
**Pull request by kpoeck**
to use, e.g.
```lisp
(let* ((file "~/quicklisp/setup.lisp"))
   (core:stat file))

5054
1464206628
33188
(let* ((file "~/quicklisp/setup.lisp")
       (fd nil))
  (with-open-file (stream file :direction :input)
    (setq fd (core::file-stream-fd stream))
  (core:fstat fd)))

5054
1464206628
33188
````

### CODE REVIEW

**Comment by Bike** [comment]
This assumes POSIX, no? I mean, we pretty much do that anyway, but maybe we should put POSIX bindings in their own package or something.

And couldn't we just have one `fstat` function that returns three values or a structure or something?

**Comment by kpoeck** [comment]
so fstat function and stat function each returning 3 values? That I can do.

**Comment by kpoeck** [comment]
Updated to define:
* core:stat (pathname) returning (values st_size st_mtime st_mode)
* core:fstat (file-descriptor) returning (values st_size st_mtime st_mode)

**Comment by kpoeck** [comment]
* I need these to implement https://github.com/xach/zacl so that  https://github.com/gendl/aserve works for clasp
* some single-threaded tests already work

**Comment by kpoeck** [comment]
* portable aserve (in the version mentionned above) works now, will publish

**Comment by Bike** [comment]
We should probably export these... but we should think about how to present a coherent API first, so I'll merge now and we can worry about that later.

**Pull request merged**
