### PR TITLE
[Wip] Return sensible error in integer-decode-float when called with a infinity value

### PR DESCRIPTION
**Pull request by kpoeck**
* issue encountered while cross-compiling sbcl (and the origin is still to be clarified)
* return sensible error instead of sigfpe as before
* added test to regression-suite

### CODE REVIEW

**Comment by Bike** [comment]
Preferably we should figure out how to transmute a SIGFPE into a floating point error, because otherwise we'd have to put checks like this on every floating point operation. I thought I had it doing that already, but evidently not. Either the error isn't one of the ones we handle, or the traps are just totally messed up. Code is here: https://github.com/clasp-developers/clasp/blob/dev/src/gctools/interrupt.cc#L256-L271

**Comment by kpoeck** [comment]
I hope in #955 I have this fixed as you intended

**Comment by Bike** [comment]
yes. is this PR dead, then? incorporating the tests would be good, but #961 precludes that.

**Comment by kpoeck** [comment]
As you said, this pr is dead. I have stored the tests locally, but as you said, we can't add them right now. I wonder whether we need something like  `(ext:issue-fixed-p :961)`

**Pull request closed without merging**
