### PR TITLE
Add core:package-add-nickname and ext:package-remove-nickname  as a safer way than rename-package to change nicknames

### PR DESCRIPTION
**Pull request by kpoeck**
* adds `core:package-add-nickname`
* check here
```lisp
(core:package-add-nickname (find-package :cl) :future-common-lisp)

("FUTURE-COMMON-LISP" "CL")
COMMON-LISP-USER> (find-package :future-common-lisp)

#<PACKAGE COMMON-LISP>
COMMON-LISP-USER> (package-nicknames (find-package :cl))               

("FUTURE-COMMON-LISP" "CL")
COMMON-LISP-USER> (find-package :common-lisp)

#<PACKAGE COMMON-LISP>
COMMON-LISP-USER> (describe (find-package :common-lisp))

#<PACKAGE COMMON-LISP> - package
 nicknames:  ("FUTURE-COMMON-LISP" "CL")
 used-by list:  (#<PACKAGE PRIMOP> #<PACKAGE INTERPRET-AST>
                 #<PACKAGE LISP-EXECUTABLE.CREATION> #<PACKAGE CLEAVIR-IR-GML>
                 #<PACKAGE CC-MIR> #<PACKAGE CC-HIR-TO-MIR>
                 #<PACKAGE CC-GENERATE-AST> #<PACKAGE CLASP-CLEAVIR-AST-TO-HIR>
                 #<PACKAGE CLASP-CLEAVIR-HIR> #<PACKAGE CLASP-CLEAVIR-AST>
                 #<PACKAGE CLASP-CLEAVIR> #<PACKAGE CCLASP-BUILD>
                 #<PACKAGE SICL-ADDITIONAL-CONDITIONS>
                 #<PACKAGE SICL-ADDITIONAL-TYPES>
                 #<PACKAGE CLEAVIR-BASIC-BLOCKS> #<PACKAGE CLEAVIR-UTILITIES>
                 #<PACKAGE CLEAVIR-HIR-TO-MIR>
                 #<PACKAGE CLEAVIR-PARTIAL-INLINING>
                 #<PACKAGE CLEAVIR-REMOVE-USELESS-INSTRUCTIONS>
                 #<PACKAGE CLEAVIR-HIR-TRANSFORMATIONS>
                 #<PACKAGE CLEAVIR-ESCAPE> #<PACKAGE CLEAVIR-TYPE-DESCRIPTORS>
                 #<PACKAGE CLEAVIR-KILDALL-TYPE-INFERENCE>
                 #<PACKAGE CLEAVIR-LIVENESS>
                 #<PACKAGE CLEAVIR-KILDALL-GRAPHVIZ> #<PACKAGE CLEAVIR-KILDALL>
                 #<PACKAGE CLEAVIR-AST-TO-HIR> #<PACKAGE CLEAVIR-IR-GRAPHVIZ>
                 #<PACKAGE CLEAVIR-IR> #<PACKAGE CLEAVIR-CST-TO-AST>
                 #<PACKAGE CLEAVIR-GENERATE-AST>
                 #<PACKAGE CLEAVIR-COMPILATION-POLICY>
                 #<PACKAGE CLEAVIR-ENVIRONMENT>
                 #<PACKAGE CLEAVIR-CODE-UTILITIES>
                 #<PACKAGE CLEAVIR-AST-TRANSFORMATIONS>
                 #<PACKAGE CLEAVIR-AST-GRAPHVIZ> #<PACKAGE CLEAVIR-AST>
                 #<PACKAGE CLEAVIR-METER> #<PACKAGE CLEAVIR-IO>
                 #<PACKAGE ECLECTOR.CONCRETE-SYNTAX-TREE>
                 #<PACKAGE ECLECTOR.PARSE-RESULT> #<PACKAGE ECLECTOR.READER>
                 #<PACKAGE ECLECTOR.READTABLE.SIMPLE>
                 #<PACKAGE ECLECTOR.READTABLE> #<PACKAGE ECLECTOR.BASE>
                 #<PACKAGE CLOSER-MOP> #<PACKAGE ALEXANDRIA.0.DEV>
                 #<PACKAGE CONCRETE-SYNTAX-TREE> #<PACKAGE ACCLIMATION>
                 #<PACKAGE STATIC-GFS> #<PACKAGE MP> #<PACKAGE LITERAL>
                 #<PACKAGE C> #<PACKAGE SB-BSD-SOCKETS> #<PACKAGE CLBIND-TEST>
                 #<PACKAGE SB-BSD-CLBIND> #<PACKAGE CORE> #<PACKAGE EXT>
                 #<PACKAGE COMPILER> #<PACKAGE CLOS> #<PACKAGE GRAY>
                 #<PACKAGE GCTOOLS> #<PACKAGE LLVM-SYS> #<PACKAGE CLBIND>
                 #<PACKAGE CLASP-FFI> #<PACKAGE SERVE-EVENT-INTERNAL>
                 #<PACKAGE SOCKETS-INTERNAL> #<PACKAGE MPI>
                 #<PACKAGE AST-TOOLING> #<PACKAGE CLANG-AST>
                 #<PACKAGE CLANG-COMPILE> #<PACKAGE COMMON-LISP-USER>)
````

### CODE REVIEW

**Comment by Bike** [comment]
What would this be used for? If it's in CORE rather than EXT, some kind of internal use?

**Comment by kpoeck** [comment]
I need this for cl-http, where most of the packages :use :future-common-lisp (future as of 1994)

Defining this in ext sounds better, so will change that

**Comment by Bike** [comment]
So just so I'm clear, `(add-package-nickname package nickname)` = `(rename-package package (package-name package) (cons nickname (package-nicknames package)))` or so? I guess that's fine. Throw in a `remove-package-nickname` as well and give them docstrings, though.

**Comment by kpoeck** [comment]
Yes, as right as you assume, so I do both changes as requested

**Comment by kpoeck** [comment]
* defined ext:package-add-nickname as requested
* defined ext:package-remove-nickname as requested
* added regression tests for both

**Comment by kpoeck** [comment]
* did add more tests than the happy path
@Bike , whenever you have time

**Pull request merged**
