### PR TITLE
Use Eclectors without-signal branch

### PR DESCRIPTION
**Pull request by kpoeck**
* as discussed on #sicl : use the without-signal branch (has been rebased and contains all latest fixes)
* tested with
  * regression tests
  * ansi-tests
  * icando-boehm

### CODE REVIEW

**Comment by Bike** [comment]
I think it would be better to target this to the master branch?

**Comment by kpoeck** [comment]
I believe I am simply not aware of a good criteria to which branch to go.

To branch bir only things that actually have to do with BIR? Then this pr needs to go to master as you say.

Please advise

**Comment by Bike** [comment]
My criterion is that there's a hopefully small chance BIR doesn't work and I chuck the whole thing, and in that eventuality I'd like things like this that would be useful regardless to remain. So yes, things that don't have to do with BIR should go to master. I can just rebase them into BIR.

**Comment by kpoeck** [comment]
ok will do as you said, so closing this and creating a new pr to master

**Pull request closed without merging**
