### PR TITLE
[Wip] Fix *PRINT-CIRCLE*

### PR DESCRIPTION
**Pull request by kpoeck**
This is a port of pr https://gitlab.com/embeddable-common-lisp/ecl/-/merge_requests/161 from ecl (just with write-object-with-circle written in lisp)
* in clasp regression-tests solves 
`unexpected success (PRINT.ARRAY.RANDOM.1.TAKE.1 PRINT.ARRAY.RANDOM.1.TAKE.2
                    PRINT.VECTOR.RANDOM.1.TAKE.1 PRINT.VECTOR.RANDOM.1.TAKE.2
                    READ-PRINT-CONSISTENCY-ARRAYS)`
* solves #706
*  `(let ((vector (vector 23))
               (*PRINT-READABLY* T)
               (*PRINT-CIRCLE* t)
               (*PRINT-PRETTY* T)
               )
           (write-to-string vector))
=> "#A(T (1) (23))"`
* `(let ((vector (vector 25 26 27))
      (*PRINT-READABLY* t)
      (*PRINT-CIRCLE* t)
      (*PRINT-PRETTY* T)
      )
  (setf (aref vector 2) vector)
  (write-to-string vector))
=> "#1=#A(T (3) (25 26 #1#))"`
* `(let ((array (make-array (list 2 2) :initial-contents '((5 6)(7 8))))
              (*PRINT-READABLY* T)
              (*PRINT-CIRCLE* t)
              (*PRINT-PRETTY* T)
              )
          (write-to-string array))
=> "#A(T (2 2) ((5 6) (7 8)))"`
* `(with-standard-io-syntax
  (let ((*PRINT-CIRCLE* T)
        (*PRINT-READABLY* T)
        (*PRINT-PRETTY* T))
    (with-output-to-string (s)
      (write #2A((3 4 5)) :stream s))))
=> "#A(T (1 3) ((3 4 5)))"`

* ansi-tests seem to fix the following `10 unexpected successes: PRINT.BACKQUOTE.RANDOM.1, PRINT.BACKQUOTE.RANDOM.5, 
   PRINT.BACKQUOTE.RANDOM.10, PRINT.BACKQUOTE.RANDOM.11, 
   PRINT.VECTOR.RANDOM.2, PRINT.VECTOR.RANDOM.3, PRINT.ARRAY.2.21, 
   PRINT.ARRAY.2.22, PRINT.ARRAY.2.23, PRINT.ARRAY.2.24.`

### CODE REVIEW

**Comment by Bike** [comment]
So basically moving circle handling into its own function instead of the pprint business? makes sense to me. But then why does it `catch 'line-limit-abbreviation-happened`?

**Comment by kpoeck** [comment]
the following errors w/o the catch:
```lisp
(WRITE #1A(#:q7po ROUND #:G1261926 LOGORC2 -33139065 aAaAAAAaBBAaBBb -2798695817 4278/65 ASSOC-IF-NOT #\? )
       :PRETTY T :LENGTH NIL :READABLY NIL :CIRCLE T :LINES 3 :RIGHT-MARGIN 25)
->
Condition of type: CONTROL-ERROR
Condition of type CONTROL-ERROR was signaled.

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

COMMON-LISP-USER>> (ext:btcl)
   0: ((LAMBDA NIL))
  25: (DEFAULT-DEBUGGER #S(CONTROL-ERROR ))
  26: (INVOKE-DEBUGGER #S(CONTROL-ERROR ))
  27: (UNIVERSAL-ERROR-HANDLER NIL CONTROL-ERROR NIL)
  30: (ERROR CONTROL-ERROR)
  36: (OUTPUT-LINE #S(PRETTY-STREAM ) #S(NEWLINE ))
  37: (MAYBE-OUTPUT #S(PRETTY-STREAM ) NIL)
  38: (ENQUEUE-NEWLINE #S(PRETTY-STREAM ) :FILL)
  39: (PPRINT-NEWLINE :FILL #S(PRETTY-STREAM ))
  40: (#:PPRINT-LOGICAL-BLOCK-170565 NIL #S(PRETTY-STREAM ))
  41: ((LAMBDA (OBJECT STREAM1)) NIL #S(PRETTY-STREAM ))
  42: (WRITE-OBJECT-WITH-CIRCLE NIL #S(PRETTY-STREAM ) #<CLOSURE-WITH-SLOTS@0x11faf0318  (LAMBDA (OBJECT STREAM1)) :type cclasp  lambda-list: (OBJECT STREAM1) :fptr 0x1159bf8e0>)
  43: (DO-PPRINT-LOGICAL-BLOCK #<CLOSURE-WITH-SLOTS@0x11fbb0798  #:PPRINT-LOGICAL-BLOCK-170565 :type cclasp  lambda-list: (#:G170564 STREAM &AUX (#:PPRINT-LOGICAL-BLOCK-LENGTH-170566 0)) :fptr 0x1159c8c40> NIL #S(PRETTY-STREAM ) #( NIL ))
  44: (PPRINT-LOGICAL-BLOCK-HELPER #<CLOSURE-WITH-SLOTS@0x11fbb0798  #:PPRINT-LOGICAL-BLOCK-170565 :type cclasp  lambda-list: (#:G170564 STREAM &AUX (#:PPRINT-LOGICAL-BLOCK-LENGTH-170566 0)) :fptr 0x1159c8c40> NIL #S(PRETTY-STREAM ) #( NIL ))
  45: ((LAMBDA (VECTOR STREAM)) #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) #S(PRETTY-STREAM ))
  46: (WRITE-OBJECT-WITH-CIRCLE #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) #S(PRETTY-STREAM ) #<CLOSURE-WITH-SLOTS@0x11ee17328  (LAMBDA (VECTOR STREAM)) :type cclasp  lambda-list: (VECTOR STREAM) :fptr 0x1159c8b90>)
  47: (WRITE-OBJECT-WITH-CIRCLE #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) #<SYNONYM-STREAM +PROCESS-STANDARD-OUTPUT+> #<CLOSURE-WITH-SLOTS@0x11ee17328  (LAMBDA (VECTOR STREAM)) :type cclasp  lambda-list: (VECTOR STREAM) :fptr 0x1159c8b90>)
  48: (PPRINT-VECTOR #<SYNONYM-STREAM +PROCESS-STANDARD-OUTPUT+> #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ))
  49: (PPRINT-ARRAY #<SYNONYM-STREAM +PROCESS-STANDARD-OUTPUT+> #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ))
  53: (WRITE #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) :PRETTY T :LENGTH NIL :READABLY NIL :CIRCLE T :LINES 3 :RIGHT-MARGIN 25)
  55: (SIMPLE-EVAL (WRITE #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) :PRETTY T :LENGTH NIL :READABLY NIL :CIRCLE T :LINES 3 :RIGHT-MARGIN 25) NIL #S(STANDARD-GENERIC-FUNCTION CCLASP-EVAL-WITH-ENV #slots[11]))
  56: (CCLASP-EVAL (WRITE #1A(#:Q7PO ROUND #:G1261926 LOGORC2 -33139065 AAAAAAAABBAABBB -2798695817 4278/65 ASSOC-IF-NOT #\? ) :PRETTY T :LENGTH NIL :READABLY NIL :CIRCLE T :LINES 3 :RIGHT-MARGIN 25) NIL)
  57: (CATCH-LAMBDA)
  59: (TPL)
  60: (CATCH-LAMBDA)
````

But the catch does not look right, letme test

**Comment by Bike** [comment]
Well it should still be somewhere, it's thrown by the pretty printer.

This is a fairly minor thing by the way, merge doesn't seem like a problem otherwise

**Comment by kpoeck** [comment]
Sorry the throw is here:
https://github.com/clasp-developers/clasp/blob/dev/src/lisp/kernel/lsp/pprint.lsp#L646

I just wonder where to catch it best

**Pull request closed without merging**
