### PR TITLE
[Wip] Define core:defconstant-equalp

### PR DESCRIPTION
**Pull request by kpoeck**
to allow `(core:defconstant-equalp +foo+ (make-array 3 :initial-contents (list 1 2 3)))`

### CODE REVIEW

**Comment by Bike** [comment]
I don't mind adding this, but where it would it be used?

**Comment by kpoeck** [comment]
For defconstant of arrays as i put in the example, they are not equal but only equalp ( apart from strings and bitvectors)

**Comment by kpoeck** [comment]
like in the issue #850: I had to put (using something unexported):
```lisp
(core::defconstant-eqx round-constants
  (make-array 10 :initial-contents (list #x01000000 #x02000000 #x04000000 #x08000000 #x10000000
                                         #x20000000 #x40000000 #x80000000 #x1B000000 #x36000000))
  equalp)
````

**Comment by Bike** [comment]
Put where? Ironclad isn't going to use anything in our CORE package. Our tests?

**Comment by kpoeck** [comment]
Core:defconstant-equal does not work for arrays, but i said that already.

I consider it bad style if i need to access a core::whatever to define a constant array. I cannot use defconstan either

**Comment by Bike** [comment]
That's not what I'm asking. I'm asking what code you are writing that needs to define equalp constants, that's all. WHERE are you defining these constant arrays. In the issue you linked it's just a test case for a bug, and the constantness probably doesn't even matter.

**Pull request closed without merging**
