### PR TITLE
Show phase for processes, define mp:process-phase

### PR DESCRIPTION
**Pull request by kpoeck**
To ease debugging:
* show the phase of a process while printing
* `mp:process-phase`

### CODE REVIEW

**Comment by Bike** [comment]
I'm not sure the phases have quite the right granularity to display to users. For example "exiting" includes processes that have in fact exited. Maybe we could pare it down to not-yet-started, running, suspended, exited?

**Comment by kpoeck** [comment]
That change certainly helped me to tackle a error while porting portable aserve, precisely because I could see that a process has exited, when it should't have.

But I am all for better granularity, so lets implement that:
_Phase = Inactive (don't know how to map)
* not-yet-started iff _Phase = Booting 
* running iff _Phase = Active
* suspended iff _Phase = Suspended
* aborted (don't know yet how to distinguish from completed)
* completed don't know yet how to distinguish from aborted)

**Comment by Bike** [comment]
Inactive is probably not-yet-started, since if I'm not mistaken that's the phase between `make-process` and `process-enable`. Booting is the phase between `process-enable` and `do_start_thread_inner` and probably just counts as active - really I'm not entirely clear why it's a separate phase, but I think for Lisp purposes it counts as running.

Aborted versus completed can be distinguished as of a change I made a few commits ago - just check the `process->_Aborted` field. That could be merged into the `_Phase` field perhaps.

**Comment by kpoeck** [comment]
Did what you proposed:
```lisp
Starting cclasp-boehm-0.4.2-2274-gdcf34384f-cst ... loading image...
Top level in: #<PROCESS TOP-LEVEL @0x111429869 Phase:Running (not enabled)>.
COMMON-LISP-USER> (mp:all-processes)

(#<PROCESS TOP-LEVEL @0x111429869 Phase:Running (not enabled)>)
COMMON-LISP-USER> (defparameter *repl* (first (mp:all-processes)))

*REPL*
COMMON-LISP-USER> *repl*

#<PROCESS TOP-LEVEL @0x111429869 Phase:Running (not enabled)>
COMMON-LISP-USER> (mp:process-active-p *repl*)

NIL
COMMON-LISP-USER> (defparameter *foo* (mp:process-run-function "A Process" #'(lambda())))

*FOO*
COMMON-LISP-USER> *foo*

#<PROCESS "A Process" @0x125228159 Phase:Completed>
COMMON-LISP-USER> (defparameter *bar* (mp:make-process "Another process" #'(lambda()(loop (mp:process-yield)))))

*BAR*
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x11d40fef9 Phase:Running (not enabled)>
COMMON-LISP-USER> (mp:process-enable  *bar*)

0
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x11d40fef9 Phase:Running (enabled)>
COMMON-LISP-USER> (mp:process-suspend  *bar*)
../../src/gctools/interrupt.cc:131 clasp_interrupt_process queuing signal

COMMON-LISP-USER> In wake_up_thread interrupt.cc:296
````

**Comment by kpoeck** [comment]
I have some additional observation with regards to processes. Since they have nothing to do with this pr, will do a new issue

**Comment by Bike** [comment]
This is just my preference, but I'd rather have just "(running)" than "Phase:Running".

I'm not sure what "enabled" means in the display. In the first few lines, how could the REPL thread, which is the only thread, not be enabled? How can a thread be running but not enabled?

**Comment by kpoeck** [comment]
The repl thread stays in `Booting`. That might be another error, but has nothing to do with this pr.

I put `Running (not enabled)`and `Running (enabled)`to be able to distinguish between threads that still need `mp:process-enable` to really run, or are already enabled.

I will drop the String Phase from __repr__  as reuested

**Comment by kpoeck** [comment]
ok, here session with the changes:
```lisp
Starting cclasp-boehm-0.4.2-2274-gdcf34384f-cst ... loading image...
Top level in: #<PROCESS TOP-LEVEL @0x115070869 (Running, not active)>.
COMMON-LISP-USER> (defparameter *repl* (first (mp:all-processes)))

*REPL*
COMMON-LISP-USER> *REPL*

#<PROCESS TOP-LEVEL @0x115070869 (Running, not active)>
COMMON-LISP-USER> (mp:process-active-p *repl*)

NIL
COMMON-LISP-USER> (defparameter *foo* (mp:process-run-function "A Process" #'(lambda())))

*FOO*
COMMON-LISP-USER> *foo*

#<PROCESS "A Process" @0x1234f8899 (Completed)>
COMMON-LISP-USER> (defparameter *bar-foo*
  (mp:make-process "Another process"
                   #'(lambda()
                       (loop
                          (mp:process-yield)
                          (let ((nada (cons 3 4))))))))

*BAR-FOO*
COMMON-LISP-USER> *bar-foo*

#<PROCESS "Another process" @0x12128e609 (Running, not active)>
COMMON-LISP-USER> (defparameter *bar*
  (mp:make-process "Another process"#'(lambda()
                                        (loop
                                           (mp:process-yield)
                                           ;;; Allocate something, so that we can be interrupted
                                           (let ((nada (cons 3 4))))))))

*BAR*
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x1211c8919 (Running, not active)>
COMMON-LISP-USER> (mp:process-active-p *bar*)

NIL
COMMON-LISP-USER> (mp:process-phase-string *bar*)

"(Running, not active)"
COMMON-LISP-USER> (mp:process-enable  *bar*)

0
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x1211c8919 (Running, active)>
COMMON-LISP-USER> (mp:process-suspend *bar*)
../../src/gctools/interrupt.cc:131 clasp_interrupt_process queuing signal

../../src/gctools/interrupt.cc:338 Wake_up_thread: 
../../src/gctools/interrupt.cc:209:handle_all_queued_interrupts Handling a signal - there are pending interrupts
../../src/gctools/interrupt.cc:211:handle_all_queued_interrupts Handling a signal: #<CLOSURE-WITH-SLOTS@0x1156b6018  SUSPEND-LOOP :type cclasp  lambda-list: NIL :fptr 0x11c179600>
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x1211c8919 (Suspended)>
COMMON-LISP-USER> (mp:process-resume  *bar*)

COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x1211c8919 (Running, active)>
COMMON-LISP-USER> (ext:quit)
````

**Comment by kpoeck** [comment]
@Bike , - when yu have time - could you please check again whether this fits

**Comment by Bike** [comment]
What I meant was that I don't think that a process that hasn't been enabled is "running". I mean it's not doing anything. Instead of "running, active" and "running, not active" it could just be "running" and "not yet started" or something. The "enable process" terminology we use might not be good here - maybe we could replace `process-enable` with `process-start` or something?

As for the REPL thread... that's weird, but unrelated, okay. I'll look at it.

**Comment by kpoeck** [comment]
Hope that we are now converged:
````
Starting cclasp-boehm-0.4.2-2274-gdcf34384f-cst ... loading image...
Top level in: #<PROCESS TOP-LEVEL @0x114873869 (Not yet started)>.
COMMON-LISP-USER> (defparameter *repl* (first (mp:all-processes)))

*REPL*
COMMON-LISP-USER> *repl*

#<PROCESS TOP-LEVEL @0x114873869 (Not yet started)>
COMMON-LISP-USER> (mp:process-active-p *repl*)

NIL
COMMON-LISP-USER> (defparameter *foo* (mp:process-run-function "A Process" #'(lambda())))

*FOO*
COMMON-LISP-USER> *foo*

#<PROCESS "A Process" @0x122c35de9 (Completed)>
COMMON-LISP-USER> (defparameter *bar-foo*
  (mp:process-run-function "Another process"
                   #'(lambda()
                       (loop
                          (mp:process-yield)
                          (let ((nada (cons 3 4))))))))

*BAR-FOO*
COMMON-LISP-USER> *bar-foo*

#<PROCESS "Another process" @0x120a87679 (Running)>
COMMON-LISP-USER> (defparameter *bar*
  (mp:make-process "Another process"#'(lambda()
                                        (loop
                                           (mp:process-yield)
                                           ;;; Allocate something, so that we can be interrupted
                                           (let ((nada (cons 3 4))))))))

*BAR*
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x122c3ad99 (Not yet started)>
COMMON-LISP-USER> (mp:process-active-p *bar*)

NIL
COMMON-LISP-USER> (mp:process-phase-string *bar*)

"(Not yet started)"
COMMON-LISP-USER> (mp:process-enable  *bar*)

0
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x122c3ad99 (Running)>
COMMON-LISP-USER> (mp:process-suspend *bar*)
../../src/gctools/interrupt.cc:131 clasp_interrupt_process queuing signal
../../src/gctools/interrupt.cc:209:handle_all_queued_interrupts Handling a signal - there are pending interrupts

In wake_up_thread interrupt.cc:296
../../src/gctools/interrupt.cc:211:handle_all_queued_interrupts Handling a signal: #<CLOSURE-WITH-SLOTS@0x114ef0478  SUSPEND-LOOP :type cclasp  lambda-list: NIL :fptr 0x11b9b6600>
COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x122c3ad99 (Suspended)>
COMMON-LISP-USER> (mp:process-resume  *bar*)

COMMON-LISP-USER> *bar*

#<PROCESS "Another process" @0x122c3ad99 (Running)>
````

**Comment by Bike** [comment]
Okay, sure.

Dunno what's going on with the REPL thread.

**Pull request merged**
